import type { Artifact, SideAgentExecution, AutomationWorkflow } from '@/shared/types/workspace'

export interface GeneratedAssistantOutput {
  textContent: string
  intent?: {
    toolName: string
    service: 'obsidian' | 'web' | 'calendar' | 'github' | 'database' | 'imagen' | 'briefing' | 'notion' | 'automation'
    status: 'executing' | 'completed'
    summaryText: string
  }
  sideAgent?: SideAgentExecution
  artifact?: Artifact
  sourceDomains?: string[]
  createdAutomation?: Omit<AutomationWorkflow, 'id' | 'totalRuns' | 'createdAt'>
}

// 1. Obsidian Vault Note Generator (Full Markdown in Aside + Executive Summary in Chat)
export function generateObsidianNoteOutput(prompt: string): GeneratedAssistantOutput {
  const docTitle = prompt.length > 45 ? prompt.slice(0, 45) + '...' : prompt
  const safeSlug =
    prompt
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .slice(0, 25) || 'note'
  const pathName = `Vault/Work/Notes/${safeSlug}.md`
  const newArtId = `art-${Date.now()}`
  const nowStr = new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })

  const markdownContent = `# ${docTitle}

> **Generated by ContextForge** · Synced to \`${pathName}\`
> **Date:** ${nowStr} · **Status:** Validated & Synced

## 🎯 Executive Summary
${prompt}

## 📝 Key Takeaways & Architecture Points
1. **Core Architectural Goal:** Establish resilient, isolated modular boundaries with zero state-leakage.
2. **Context Grounding:** Cross-referenced against internal Obsidian knowledge vaults and RFC specs.
3. **Integration Strategy:** Bi-directional sync via MCP (Model Context Protocol).

## ⚡ Action Items & Next Steps
- [ ] Implement core interfaces and strict typing.
- [ ] Verify test suite regression coverage (target >90%).
- [ ] Run security threat-model audit.
- [ ] Review during tomorrow's team sync.

---
*Note: This note is active in your local Obsidian vault and can be edited anytime.*`

  const newArtifact: Artifact = {
    id: newArtId,
    type: 'markdown_doc',
    title: docTitle,
    content: markdownContent,
    locationPath: pathName,
    serviceOrigin: 'obsidian',
    createdAt: 'Just now',
    updatedAt: 'Just now',
    wordCount: markdownContent.split(/\s+/).filter(Boolean).length,
  }

  const sideAgent: SideAgentExecution = {
    id: `sa-action-${Date.now()}`,
    agentId: 'agent-action',
    agentName: 'Action Agent',
    agentRole: 'Side Agent: Document & Vault Mutator',
    avatarColor: 'bg-[#9fbbe0]',
    taskGoal: `Format markdown and write note to "${pathName}"`,
    actionType: 'action_write',
    targetResource: pathName,
    status: 'completed',
    riskLevel: 'low_risk',
    executionTimeMs: 380,
    tokensUsed: { input: 240, output: 95 },
    logs: [
      `[ActionAgent] Initializing isolated worker execution...`,
      `[ActionAgent] Connecting to vault at: obsidian://vault/Engineering-HQ`,
      `[ActionAgent] Generating YAML frontmatter metadata and backlinks...`,
      `[ActionAgent] Writing payload to: ${pathName}`,
      `[ActionAgent] Verification: File integrity OK (0 errors). Worker completed.`,
    ],
    summary: `Formatted and written note to Obsidian vault at ${pathName}`,
    filesModified: [pathName],
    artifactId: newArtId,
  }

  const textContent = `Saya telah mendelegasikan penyusunan dokumen ke **Action Agent**. Dokumen lengkap telah diformat dan dibuka di panel **Workspace Aside** sebelah kanan.

### 📋 Ringkasan Eksekutif Rencana:
- **Dokumen:** \`${docTitle}\`
- **Target Vault:** \`${pathName}\`
- **Poin Utama:** Isolasi modular boundary, sinkronisasi bi-directional MCP, dan checklist aksi.

*Anda dapat membaca, mengedit, atau men-download dokumen lengkapnya langsung pada panel editor di sebelah kanan.*`

  return {
    textContent,
    intent: {
      toolName: 'dispatch_side_agent',
      service: 'obsidian',
      status: 'completed',
      summaryText: `Obsidian Note Created: ${pathName}`,
    },
    sideAgent,
    artifact: newArtifact,
  }
}

// 2. Scheduled Automation Generator (Background Workflow - Zero Popups)
export function generateAutomationScheduledOutput(prompt: string): GeneratedAssistantOutput {
  const lower = prompt.toLowerCase()

  // 1. Natural Language Time to Cron Extraction
  let cron = '0 8 * * *'
  let timeLabel = 'Every day at 08:00 AM (08:00 WIB)'
  if (lower.includes('jam 8') || lower.includes('08:00') || lower.includes('8 pagi') || lower.includes('8 am')) {
    cron = '0 8 * * *'
    timeLabel = 'Every day at 08:00 AM'
  } else if (lower.includes('jam 9') || lower.includes('09:00') || lower.includes('9 pagi') || lower.includes('9 am')) {
    cron = '0 9 * * *'
    timeLabel = 'Every day at 09:00 AM'
  } else if (lower.includes('senin') || lower.includes('monday')) {
    cron = '0 9 * * 1'
    timeLabel = 'Every Monday at 09:00 AM'
  } else if (lower.includes('6 jam') || lower.includes('every 6 hours')) {
    cron = '0 */6 * * *'
    timeLabel = 'Every 6 Hours'
  } else if (lower.includes('jumat') || lower.includes('friday')) {
    cron = '0 17 * * 5'
    timeLabel = 'Every Friday at 05:00 PM'
  }

  // 2. Service & MCP Connector Matching (Strictly Notion & Obsidian)
  let name = 'Daily Notion Tasks Briefing'
  let description = `Queries Notion Task Board every morning (${timeLabel}), extracts priority items, and prepares daily focus briefing.`
  let mcpServerId = 'int-notion-mcp'
  let mcpTools = ['notion_get_tasks', 'notion_read_page', 'notion_search']
  let agentId = 'agent-action'
  let agentName = 'Action Agent (Notion Worker)'

  if (lower.includes('obsidian') || lower.includes('catatan') || lower.includes('note') || lower.includes('journal')) {
    name = 'Daily Morning Obsidian Briefing & Journaling'
    description = `Creates and updates Obsidian daily notes (${timeLabel}) with linked tasks, focus items, and contextual backlinks.`
    mcpServerId = 'int-obsidian-vault-mcp'
    mcpTools = ['obsidian_create_daily_note', 'obsidian_vault_writer', 'obsidian_vault_reader']
    agentId = 'agent-action'
    agentName = 'Action Agent (Obsidian Vault Worker)'
  } else if (lower.includes('notion') || lower.includes('tugas') || lower.includes('task')) {
    name = 'Daily Notion Tasks Briefing'
    description = `Queries Notion Task Board every morning (${timeLabel}), extracts priority items, and prepares daily focus briefing.`
    mcpServerId = 'int-notion-mcp'
    mcpTools = ['notion_get_tasks', 'notion_read_page', 'notion_search']
    agentId = 'agent-action'
    agentName = 'Action Agent (Notion Worker)'
  }

  const createdAutomation: Omit<AutomationWorkflow, 'id' | 'totalRuns' | 'createdAt'> = {
    name,
    description,
    agentId,
    agentName,
    mcpServerId,
    mcpTools,
    triggerType: 'schedule',
    scheduleCron: cron,
    scheduleLabel: timeLabel,
    promptTemplate: `Tinjau seluruh data dan tugas terkait dari konektor MCP (${mcpServerId}). Buatkan ringkasan prioritas tinggi untuk hari ini ({{today}}).`,
    guardrailStrictHITL: false,
    isActive: true,
  }

  const textContent = `⏰ **Automation Berhasil Dijadwalkan!**

Saya telah mendaftarkan workflow automasi baru di latar belakang:
- **Nama Workflow:** \`${name}\`
- **Jadwal Eksekusi:** **${timeLabel}** (\`${cron}\`)
- **Worker Agent:** **${agentName}**
- **MCP Tools:** ${mcpTools.map((t) => `\`${t}\``).join(', ')}

*Workflow ini akan berjalan secara mandiri di latar belakang tanpa membebani jendela percakapan. Anda dapat mengelolanya kapan saja di menu [Automations](/automation).*`

  return {
    textContent,
    intent: {
      toolName: 'create_scheduled_automation',
      service: 'automation',
      status: 'completed',
      summaryText: `Automation Created: ${name} (${cron})`,
    },
    createdAutomation,
  }
}

// 3. Instant Chat Task: Notion Tasks Query
export function generateNotionTaskOutput(prompt: string): GeneratedAssistantOutput {
  void prompt
  const nowStr = new Date().toLocaleDateString('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })

  const textContent = `📋 **Ringkasan Tugas Notion Anda (${nowStr}):**

Saya telah memeriksa database tugas Notion Anda via **Notion MCP** (\`notion_get_tasks\`):

| Prioritas | Nama Tugas | Status | Deadline |
| :--- | :--- | :--- | :--- |
| 🔴 **High** | Finalisasi OAuth2 PKCE Flow & Security Check | In Progress | Hari ini, 16:00 |
| 🔴 **High** | Code Review PR #42: Agentic Automation Engine | In Progress | Hari ini, 18:00 |
| 🟡 **Medium** | Migrasi PostgreSQL native schema & index | To Do | Besok |
| 🟢 **Low** | Perbarui dokumentasi TDD & Architecture Diagram | Backlog | 24 Agu |

### 💡 Rekomendasi Fokus Hari Ini:
Fokuskan 2 jam pertama pada **OAuth2 PKCE Flow** dan **Code Review PR #42**. Semua dependensi backend sudah siap di *local sandbox*.`

  const sideAgent: SideAgentExecution = {
    id: `sa-notion-${Date.now()}`,
    agentId: 'agent-action',
    agentName: 'Action Agent (Notion Worker)',
    agentRole: 'Side Agent: Notion Workspace Connector',
    avatarColor: 'bg-[#0081a7]',
    taskGoal: 'Query Notion Task Board database via MCP Protocol',
    actionType: 'api_mutate',
    targetResource: 'Notion Database: Product Engineering Tasks',
    status: 'completed',
    riskLevel: 'low_risk',
    executionTimeMs: 420,
    tokensUsed: { input: 190, output: 80 },
    logs: [
      `[NotionWorker] Connecting to Notion MCP endpoint: https://mcp.notion.com/mcp`,
      `[NotionWorker] Querying database: "Product Engineering Tasks"... 200 OK`,
      `[NotionWorker] Found 4 active tasks (2 High Priority, 1 Medium, 1 Backlog)`,
      `[NotionWorker] Synthesizing focus summary for user... Complete.`,
    ],
    summary: 'Fetched 4 active tasks from Notion workspace via MCP protocol.',
  }

  return {
    textContent,
    intent: {
      toolName: 'notion_get_tasks',
      service: 'notion',
      status: 'completed',
      summaryText: 'Notion MCP: 4 Active Tasks Retrieved',
    },
    sideAgent,
  }
}

// 4. Code Mutation & CLI Generator (Full Code in Aside + Executive Summary in Chat)
export function generateCodeMutationOutput(prompt: string): GeneratedAssistantOutput {
  const fileTarget =
    prompt.includes('.ts') || prompt.includes('.js') || prompt.includes('.py')
      ? prompt.split(' ').find((w) => w.includes('.')) || 'src/middleware/auth.ts'
      : 'src/modules/auth.ts'
  const newArtId = `art-code-${Date.now()}`

  const generatedCode = `import { Request, Response, NextFunction } from 'express'
import jwt from 'jsonwebtoken'

export interface AuthenticatedUser {
  userId: string
  role: 'admin' | 'architect' | 'developer'
  email: string
}

export interface AuthRequest extends Request {
  user?: AuthenticatedUser
}

/**
 * JWT Authentication Middleware
 * Enforces strict Bearer token header verification with AST validation
 */
export function verifyAuthToken(req: AuthRequest, res: Response, next: NextFunction): void {
  const authHeader = req.headers.authorization

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.status(401).json({ error: 'Unauthorized: Missing or invalid token format' })
    return
  }

  const token = authHeader.slice(7)
  const secret = process.env.JWT_SECRET || 'contextforge-secure-dev-key'

  try {
    const decoded = jwt.verify(token, secret) as AuthenticatedUser
    req.user = decoded
    next()
  } catch (err) {
    res.status(403).json({ error: 'Forbidden: Invalid or expired token' })
  }
}`

  const newArtifact: Artifact = {
    id: newArtId,
    type: 'code_patch',
    title: `Source Code: ${fileTarget}`,
    content: `\`\`\`typescript\n${generatedCode}\n\`\`\``,
    locationPath: fileTarget,
    serviceOrigin: 'github',
    createdAt: 'Just now',
    wordCount: generatedCode.split(/\s+/).filter(Boolean).length,
    diffs: [
      {
        file: fileTarget,
        additions: 32,
        deletions: 0,
        newCode: generatedCode,
      },
    ],
  }

  const sideAgent: SideAgentExecution = {
    id: `sa-cli-${Date.now()}`,
    agentId: 'agent-code-reviewer',
    agentName: 'CLI & Code Sandbox Runner',
    agentRole: 'Side Agent: Terminal & File Execution',
    avatarColor: 'bg-[#c0a8dd]',
    taskGoal: `Generate, write, and verify code for "${fileTarget}"`,
    actionType: 'create_file',
    targetResource: fileTarget,
    status: 'completed',
    riskLevel: 'medium_risk',
    executionTimeMs: 1120,
    tokensUsed: { input: 410, output: 165 },
    logs: [
      `[CodeSandbox] Spawning ephemeral Docker execution container...`,
      `[CodeSandbox] Writing source file to: ${fileTarget}`,
      `[CodeSandbox] Running TypeScript AST compiler & syntax check... PASS`,
      `[CodeSandbox] Running unit test runner: vitest run ${fileTarget}... PASS (2 tests passed)`,
      `[CodeSandbox] Atomic patch created. Container teardown complete.`,
    ],
    summary: `Created ${fileTarget} with 32 lines of verified TypeScript code. Syntax & test suite passed.`,
    filesModified: [fileTarget],
    diffPreview: `+ export function verifyAuthToken(req: AuthRequest, res: Response, next: NextFunction) {\n+   const authHeader = req.headers.authorization;\n+   if (!authHeader?.startsWith('Bearer ')) return res.status(401)...;\n+ }`,
    artifactId: newArtId,
  }

  const textContent = `Saya telah mendelegasikan penulisan kode ke **CLI & Code Sandbox Runner**. File lengkap telah dibuat dan dibuka di panel **Workspace Aside** sebelah kanan.

### 🔍 Ringkasan Implementasi (\`${fileTarget}\`):
- **TypeScript Strict Typing:** Interface \`AuthRequest\` dan \`AuthenticatedUser\`.
- **Security Boundary:** Verifikasi Bearer Token otomatis dengan error boundaries (401 & 403).
- **Sandbox Verification:** Lolos validasi AST dan uji unit test suite (*2 tests passed*).

*Anda dapat melihat kode lengkap, diff perubahan, dan men-download file langsung di panel editor sebelah kanan.*`

  return {
    textContent,
    intent: {
      toolName: 'dispatch_side_agent',
      service: 'github',
      status: 'completed',
      summaryText: `Side Agent: File Created (${fileTarget})`,
    },
    sideAgent,
    artifact: newArtifact,
  }
}

// 5. Web Research & Grounding Generator (Direct Comprehensive Answer + Citations in Chat)
export function generateWebResearchOutput(prompt: string): GeneratedAssistantOutput {
  const synthesisContent = `### 🌐 Research Summary: ${prompt}

Berdasarkan analisis live search dari beberapa sumber terverifikasi di tahun 2026:

1. **Pemisahan Peran Dual-Agent (Privilege Separation):**
   Arsitektur AI modern memisahkan **Main Orchestrator Agent** (bertugas melakukan penalaran, analisis, dan pencarian web dalam mode *read-only*) dari **Side Execution Agents** (yang bertugas mengeksekusi file, CLI, dan mutasi data di sandbox terisolasi).
   
2. **Keuntungan Keamanan (Prompt Injection Shielding):**
   Dengan membatasi Main Agent hanya pada mode baca (*read-only*), risiko *indirect prompt injection* dari website berbahaya dapat dinetralisir sepenuhnya karena Main Agent tidak memiliki akses langsung ke shell atau sistem file.

3. **Efisiensi Token & Context Hygiene:**
   Log terminal mentah dan riwayat eksekusi hanya diproses di subagent sementara (*ephemeral worker*), sehingga context window chat utama tetap bersih dan tidak cepat membengkak.`

  const sourceDomains = ['TechCrunch AI (2026)', 'Anthropic Research Blog', 'Model Context Protocol Specs', 'Google Cloud AI Architecture']

  const textContent = `${synthesisContent}\n\n*Informasi ini diverifikasi langsung melalui 4 sumber web terpercaya.*`

  return {
    textContent,
    sourceDomains,
  }
}

// 6. Calendar Reminder Generator
export function generateCalendarScheduleOutput(prompt: string): GeneratedAssistantOutput {
  const reminderTitle = prompt.length > 50 ? prompt.slice(0, 50) + '...' : prompt

  const sideAgent: SideAgentExecution = {
    id: `sa-cal-${Date.now()}`,
    agentId: 'agent-db-platform',
    agentName: 'Calendar & Workflow Worker',
    agentRole: 'Side Agent: Calendar & API Mutator',
    avatarColor: 'bg-[#9fc9a2]',
    taskGoal: `Schedule event "${reminderTitle}" in Google Calendar API`,
    actionType: 'calendar_schedule',
    targetResource: 'Google Calendar (Primary)',
    status: 'completed',
    riskLevel: 'low_risk',
    executionTimeMs: 290,
    tokensUsed: { input: 180, output: 75 },
    logs: [
      `[CalendarWorker] Authenticating with Google Calendar API v3...`,
      `[CalendarWorker] Creating event payload: "${reminderTitle}" @ Tomorrow 09:00 AM...`,
      `[CalendarWorker] Dispatching API POST /calendars/primary/events... 200 OK`,
      `[CalendarWorker] Setting push notification alarm (10m before event)... Done.`,
    ],
    summary: `Scheduled event "${reminderTitle}" in Google Calendar with 10-minute alarm.`,
  }

  const textContent = `📅 **Jadwal Berhasil Dibuat!**\n\nSaya telah mendelegasikan penjadwalan ke **Calendar & Workflow Worker** Side Agent:\n- **Acara:** ${reminderTitle}\n- **Waktu:** Besok, 09:00 AM\n- **Kalender:** Primary Google Calendar\n- **Notifikasi:** Alarm aktif 10 menit sebelum acara.`

  return {
    textContent,
    intent: {
      toolName: 'dispatch_side_agent',
      service: 'calendar',
      status: 'completed',
      summaryText: `Side Agent: Calendar Scheduled (${reminderTitle})`,
    },
    sideAgent,
  }
}

// 7. Visual Asset Generator (Image / Diagram)
export function generateVisualAssetOutput(prompt: string): GeneratedAssistantOutput {
  const imageTitle = prompt.length > 40 ? prompt.slice(0, 40) + '...' : prompt
  const newArtId = `art-img-${Date.now()}`
  const sampleImageSvg = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="800" height="450" viewBox="0 0 800 450"><defs><linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%231a1a24"/><stop offset="50%" stop-color="%232b2250"/><stop offset="100%" stop-color="%23ff5e00"/></linearGradient></defs><rect width="800" height="450" fill="url(%23g)" rx="24"/><circle cx="400" r="70" fill="%23ffffff" fill-opacity="0.1" stroke="%23ff5e00" stroke-width="3"/><path d="M360,180 L440,180 M400,140 L400,220" stroke="%23ffffff" stroke-width="3" stroke-linecap="round"/><text x="400" y="300" fill="%23ffffff" font-family="system-ui, sans-serif" font-size="20" font-weight="bold" text-anchor="middle">ContextForge AI Generator</text><text x="400" y="335" fill="%23ffb088" font-family="monospace" font-size="13" text-anchor="middle">${encodeURIComponent(prompt.slice(0, 45))}</text></svg>`

  const newArtifact: Artifact = {
    id: newArtId,
    type: 'image_asset',
    title: `Generated: ${imageTitle}`,
    content: `# Visual Asset: ${imageTitle}\n\n![Design Preview](${sampleImageSvg})\n\n- **Model:** Google Imagen 3 / Flux.1\n- **Resolution:** 1024x1024 (HD)\n`,
    imageUrl: sampleImageSvg,
    imagePrompt: prompt,
    serviceOrigin: 'imagen',
    createdAt: 'Just now',
  }

  const sideAgent: SideAgentExecution = {
    id: `sa-img-${Date.now()}`,
    agentId: 'agent-frontend-arch',
    agentName: 'Visual & Asset Generator',
    agentRole: 'Side Agent: GPU Asset Renderer',
    avatarColor: 'bg-[#ff5e00]',
    taskGoal: `Render visual asset: "${imageTitle}"`,
    actionType: 'image_render',
    targetResource: 'GPU Pipeline (1024x1024 SVG/PNG)',
    status: 'completed',
    riskLevel: 'low_risk',
    executionTimeMs: 1450,
    tokensUsed: { input: 320, output: 85 },
    logs: [
      `[VisualWorker] Initializing GPU rendering pipeline...`,
      `[VisualWorker] Compiling prompt embeddings and style modifiers...`,
      `[VisualWorker] Diffusion steps completed (24/24 steps)...`,
      `[VisualWorker] Safety classifier scan: Clean (0 warnings). Artifact saved.`,
    ],
    summary: `High-resolution visual design rendered and stored as SVG/PNG asset.`,
    artifactId: newArtId,
  }

  const textContent = `🎨 **Visual Asset Berhasil Di-render!**\n\nDesain visual untuk **"${imageTitle}"** telah selesai dibuat oleh GPU Side Agent:\n\n![Visual Preview](${sampleImageSvg})\n\n- **Resolusi:** 1024x1024 HD (SVG/PNG)\n- **Render Engine:** GPU Diffusion Sandbox (1.45s)`

  return {
    textContent,
    intent: {
      toolName: 'dispatch_side_agent',
      service: 'imagen',
      status: 'completed',
      summaryText: `Side Agent: Visual Asset Generated (${imageTitle})`,
    },
    sideAgent,
    artifact: newArtifact,
  }
}

// 8. Direct Reasoning & Architecture Analysis (Pure Read-Only)
export function generateGeneralReasoningOutput(prompt: string): GeneratedAssistantOutput {
  const lower = prompt.toLowerCase()

  // 1. Check for background automation intent (Recurring time / cron schedule)
  if (
    (lower.includes('setiap') || lower.includes('tiap') || lower.includes('every') || lower.includes('jadwalkan') || lower.includes('schedule')) &&
    (lower.includes('jam') || lower.includes('pagi') || lower.includes('sore') || lower.includes('malam') || lower.includes('daily') || lower.includes('hari') || lower.includes('minggu') || lower.includes('senin'))
  ) {
    return generateAutomationScheduledOutput(prompt)
  }

  // 2. Check for instant Chat Task on Notion
  if (lower.includes('notion') && (lower.includes('tugas') || lower.includes('task') || lower.includes('cek') || lower.includes('lihat') || lower.includes('daftar'))) {
    return generateNotionTaskOutput(prompt)
  }

  // 3. Check for Obsidian note creation
  if (lower.includes('obsidian') || lower.includes('buat catatan') || lower.includes('buat note') || lower.includes('tulis catatan')) {
    return generateObsidianNoteOutput(prompt)
  }

  // 4. Check for code mutation
  if (lower.includes('kode') || lower.includes('code') || lower.includes('typescript') || lower.includes('script') || lower.includes('function')) {
    return generateCodeMutationOutput(prompt)
  }

  // 5. Default General Reasoning Output
  let analysis = `Berikut adalah analisis mendalam terkait: **"${prompt}"**:\n\n`

  if (lower.includes('microservices') || lower.includes('monolith')) {
    analysis += `### 🏛️ Perbandingan Arsitektur: Microservices vs Modular Monolith

| Kriteria | Modular Monolith | Microservices |
| :--- | :--- | :--- |
| **Kompleksitas Operasional** | 🟢 Rendah (1 deployment pipeline) | 🔴 Tinggi (K8s, service mesh, tracing) |
| **Batas Domain (Boundaries)**| 🟢 Modul terpisah di satu repo | 🟢 Service terpisah di repo/container |
| **Kecepatan Development**   | 🚀 Sangat cepat untuk tim < 25 org | ⚠️ Butuh koordinasi API contract |
| **Latensi Antar-Modul**     | ⚡ In-memory function call (~0ms) | 🌐 Network call / gRPC (5-50ms) |

### 💡 Rekomendasi untuk ContextForge:
Mulai dengan **Modular Monolith** terlebih dahulu. Pisahkan domain code (Chat, Agents, Knowledge, Integrations) ke dalam modul TypeScript yang terisolasi dengan public interface yang jelas. Anda selalu bisa memecahnya menjadi microservice independen ketika traffic atau tim berkembang.`
  } else {
    analysis += `Sebagai **Personal Assistant Agent**, saya siap mendampingi Anda memahami goal, merencanakan langkah, dan mengoordinasikan berbagai kapabilitas agen/tool untuk mencapai target Anda (dalam mode *read-only* yang aman).\n\n1. **Prinsip Utama:** Setiap kebutuhan eksekusi (seperti membuat catatan di Obsidian, menulis kode, atau menjalankan aksi) akan didelegasikan secara terisolasi ke specialized worker.\n2. **Kesiapan Aksi:** Jika Anda ingin saya membuatkan catatan rangkuman di Obsidian, melakukan riset mendalam, atau merencanakan arsitektur, cukup ketik instruksi atau goal Anda.`
  }

  return {
    textContent: analysis,
  }
}
