import type { Artifact, SideAgentExecution } from '@/shared/types/workspace'

export interface GeneratedAssistantOutput {
  textContent: string
  intent?: {
    toolName: string
    service: 'obsidian' | 'web' | 'calendar' | 'github' | 'database' | 'imagen' | 'briefing'
    status: 'executing' | 'completed'
    summaryText: string
  }
  sideAgent?: SideAgentExecution
  artifact?: Artifact
  sourceDomains?: string[]
}

// 1. Obsidian Vault Note Generator (Full Markdown in Aside + Executive Summary in Chat)
export function generateObsidianNoteOutput(prompt: string): GeneratedAssistantOutput {
  const docTitle = prompt.length > 45 ? prompt.slice(0, 45) + '...' : prompt
  const safeSlug =
    prompt
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .slice(0, 25) || 'note'
  const pathName = `Vault/Work/Notes/${safeSlug}.md`
  const newArtId = `art-${Date.now()}`
  const nowStr = new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })

  const markdownContent = `# ${docTitle}

> **Generated by ContextForge** · Synced to \`${pathName}\`
> **Date:** ${nowStr} · **Status:** Validated & Synced

## 🎯 Executive Summary
${prompt}

## 📝 Key Takeaways & Architecture Points
1. **Core Architectural Goal:** Establish resilient, isolated modular boundaries with zero state-leakage.
2. **Context Grounding:** Cross-referenced against internal Obsidian knowledge vaults and RFC specs.
3. **Integration Strategy:** Bi-directional sync via MCP (Model Context Protocol).

## ⚡ Action Items & Next Steps
- [ ] Implement core interfaces and strict typing.
- [ ] Verify test suite regression coverage (target >90%).
- [ ] Run security threat-model audit.
- [ ] Review during tomorrow's team sync.

---
*Note: This note is active in your local Obsidian vault and can be edited anytime.*`

  const newArtifact: Artifact = {
    id: newArtId,
    type: 'markdown_doc',
    title: docTitle,
    content: markdownContent,
    locationPath: pathName,
    serviceOrigin: 'obsidian',
    createdAt: 'Just now',
    updatedAt: 'Just now',
    wordCount: markdownContent.split(/\s+/).filter(Boolean).length,
  }

  const sideAgent: SideAgentExecution = {
    id: `sa-obs-${Date.now()}`,
    agentId: 'agent-doc-crawl',
    agentName: 'Obsidian Vault Worker',
    agentRole: 'Side Agent: Vault & Document Writer',
    avatarColor: 'bg-[#9fbbe0]',
    taskGoal: `Format markdown and write note to "${pathName}"`,
    actionType: 'obsidian_write',
    targetResource: pathName,
    status: 'completed',
    riskLevel: 'low_risk',
    executionTimeMs: 380,
    tokensUsed: { input: 240, output: 95 },
    logs: [
      `[ObsidianWorker] Initializing isolated worker execution...`,
      `[ObsidianWorker] Connecting to vault at: obsidian://vault/Engineering-HQ`,
      `[ObsidianWorker] Generating YAML frontmatter metadata and backlinks...`,
      `[ObsidianWorker] Writing payload to: ${pathName}`,
      `[ObsidianWorker] Verification: File integrity OK (0 errors). Worker terminated.`,
    ],
    summary: `Formatted and written note to Obsidian vault at ${pathName}`,
    filesModified: [pathName],
    artifactId: newArtId,
  }

  // Executive summary in Chat while the full markdown note is opened in the Aside Panel!
  const textContent = `Saya telah mendelegasikan penyusunan dokumen ke **Obsidian Vault Worker**. Dokumen lengkap telah diformat dan dibuka di panel **Workspace Aside** sebelah kanan.

### 📋 Ringkasan Eksekutif Rencana:
- **Dokumen:** \`${docTitle}\`
- **Target Vault:** \`${pathName}\`
- **Poin Utama:** Isolasi modular boundary, sinkronisasi bi-directional MCP, dan checklist aksi.

*Anda dapat membaca, mengedit, atau men-download dokumen lengkapnya langsung pada panel editor di sebelah kanan.*`

  return {
    textContent,
    intent: {
      toolName: 'dispatch_side_agent',
      service: 'obsidian',
      status: 'completed',
      summaryText: `Obsidian Note Created: ${pathName}`,
    },
    sideAgent,
    artifact: newArtifact,
  }
}

// 2. Code Mutation & CLI Generator (Full Code in Aside + Executive Summary in Chat)
export function generateCodeMutationOutput(prompt: string): GeneratedAssistantOutput {
  const fileTarget =
    prompt.includes('.ts') || prompt.includes('.js') || prompt.includes('.py')
      ? prompt.split(' ').find((w) => w.includes('.')) || 'src/middleware/auth.ts'
      : 'src/modules/auth.ts'
  const newArtId = `art-code-${Date.now()}`

  const generatedCode = `import { Request, Response, NextFunction } from 'express'
import jwt from 'jsonwebtoken'

export interface AuthenticatedUser {
  userId: string
  role: 'admin' | 'architect' | 'developer'
  email: string
}

export interface AuthRequest extends Request {
  user?: AuthenticatedUser
}

/**
 * JWT Authentication Middleware
 * Enforces strict Bearer token header verification with AST validation
 */
export function verifyAuthToken(req: AuthRequest, res: Response, next: NextFunction): void {
  const authHeader = req.headers.authorization

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.status(401).json({ error: 'Unauthorized: Missing or invalid token format' })
    return
  }

  const token = authHeader.slice(7)
  const secret = process.env.JWT_SECRET || 'contextforge-secure-dev-key'

  try {
    const decoded = jwt.verify(token, secret) as AuthenticatedUser
    req.user = decoded
    next()
  } catch (err) {
    res.status(403).json({ error: 'Forbidden: Invalid or expired token' })
  }
}`

  const newArtifact: Artifact = {
    id: newArtId,
    type: 'code_patch',
    title: `Source Code: ${fileTarget}`,
    content: `\`\`\`typescript\n${generatedCode}\n\`\`\``,
    locationPath: fileTarget,
    serviceOrigin: 'github',
    createdAt: 'Just now',
    wordCount: generatedCode.split(/\s+/).filter(Boolean).length,
    diffs: [
      {
        file: fileTarget,
        additions: 32,
        deletions: 0,
        newCode: generatedCode,
      },
    ],
  }

  const sideAgent: SideAgentExecution = {
    id: `sa-cli-${Date.now()}`,
    agentId: 'agent-code-reviewer',
    agentName: 'CLI & Code Sandbox Runner',
    agentRole: 'Side Agent: Terminal & File Execution',
    avatarColor: 'bg-[#c0a8dd]',
    taskGoal: `Generate, write, and verify code for "${fileTarget}"`,
    actionType: 'create_file',
    targetResource: fileTarget,
    status: 'completed',
    riskLevel: 'medium_risk',
    executionTimeMs: 1120,
    tokensUsed: { input: 410, output: 165 },
    logs: [
      `[CodeSandbox] Spawning ephemeral Docker execution container...`,
      `[CodeSandbox] Writing source file to: ${fileTarget}`,
      `[CodeSandbox] Running TypeScript AST compiler & syntax check... PASS`,
      `[CodeSandbox] Running unit test runner: vitest run ${fileTarget}... PASS (2 tests passed)`,
      `[CodeSandbox] Atomic patch created. Container teardown complete.`,
    ],
    summary: `Created ${fileTarget} with 32 lines of verified TypeScript code. Syntax & test suite passed.`,
    filesModified: [fileTarget],
    diffPreview: `+ export function verifyAuthToken(req: AuthRequest, res: Response, next: NextFunction) {\n+   const authHeader = req.headers.authorization;\n+   if (!authHeader?.startsWith('Bearer ')) return res.status(401)...;\n+ }`,
    artifactId: newArtId,
  }

  const textContent = `Saya telah mendelegasikan penulisan kode ke **CLI & Code Sandbox Runner**. File lengkap telah dibuat dan dibuka di panel **Workspace Aside** sebelah kanan.

### 🔍 Ringkasan Implementasi (\`${fileTarget}\`):
- **TypeScript Strict Typing:** Interface \`AuthRequest\` dan \`AuthenticatedUser\`.
- **Security Boundary:** Verifikasi Bearer Token otomatis dengan error boundaries (401 & 403).
- **Sandbox Verification:** Lolos validasi AST dan uji unit test suite (*2 tests passed*).

*Anda dapat melihat kode lengkap, diff perubahan, dan men-download file langsung di panel editor sebelah kanan.*`

  return {
    textContent,
    intent: {
      toolName: 'dispatch_side_agent',
      service: 'github',
      status: 'completed',
      summaryText: `Side Agent: File Created (${fileTarget})`,
    },
    sideAgent,
    artifact: newArtifact,
  }
}

// 3. Web Research & Grounding Generator (Direct Comprehensive Answer + Citations in Chat)
export function generateWebResearchOutput(prompt: string): GeneratedAssistantOutput {
  const synthesisContent = `### 🌐 Research Summary: ${prompt}

Berdasarkan analisis live search dari beberapa sumber terverifikasi di tahun 2026:

1. **Pemisahan Peran Dual-Agent (Privilege Separation):**
   Arsitektur AI modern memisahkan **Main Orchestrator Agent** (bertugas melakukan penalaran, analisis, dan pencarian web dalam mode *read-only*) dari **Side Execution Agents** (yang bertugas mengeksekusi file, CLI, dan mutasi data di sandbox terisolasi).
   
2. **Keuntungan Keamanan (Prompt Injection Shielding):**
   Dengan membatasi Main Agent hanya pada mode baca (*read-only*), risiko *indirect prompt injection* dari website berbahaya dapat dinetralisir sepenuhnya karena Main Agent tidak memiliki akses langsung ke shell atau sistem file.

3. **Efisiensi Token & Context Hygiene:**
   Log terminal mentah dan riwayat eksekusi hanya diproses di subagent sementara (*ephemeral worker*), sehingga context window chat utama tetap bersih dan tidak cepat membengkak.`

  const sourceDomains = ['TechCrunch AI (2026)', 'Anthropic Research Blog', 'Model Context Protocol Specs', 'Google Cloud AI Architecture']

  const textContent = `${synthesisContent}\n\n*Informasi ini diverifikasi langsung melalui 4 sumber web terpercaya.*`

  return {
    textContent,
    sourceDomains,
  }
}

// 4. Calendar Reminder Generator
export function generateCalendarScheduleOutput(prompt: string): GeneratedAssistantOutput {
  const reminderTitle = prompt.length > 50 ? prompt.slice(0, 50) + '...' : prompt

  const sideAgent: SideAgentExecution = {
    id: `sa-cal-${Date.now()}`,
    agentId: 'agent-db-platform',
    agentName: 'Calendar & Workflow Worker',
    agentRole: 'Side Agent: Calendar & API Mutator',
    avatarColor: 'bg-[#9fc9a2]',
    taskGoal: `Schedule event "${reminderTitle}" in Google Calendar API`,
    actionType: 'calendar_schedule',
    targetResource: 'Google Calendar (Primary)',
    status: 'completed',
    riskLevel: 'low_risk',
    executionTimeMs: 290,
    tokensUsed: { input: 180, output: 75 },
    logs: [
      `[CalendarWorker] Authenticating with Google Calendar API v3...`,
      `[CalendarWorker] Creating event payload: "${reminderTitle}" @ Tomorrow 09:00 AM...`,
      `[CalendarWorker] Dispatching API POST /calendars/primary/events... 200 OK`,
      `[CalendarWorker] Setting push notification alarm (10m before event)... Done.`,
    ],
    summary: `Scheduled event "${reminderTitle}" in Google Calendar with 10-minute alarm.`,
  }

  const textContent = `📅 **Jadwal Berhasil Dibuat!**\n\nSaya telah mendelegasikan penjadwalan ke **Calendar & Workflow Worker** Side Agent:\n- **Acara:** ${reminderTitle}\n- **Waktu:** Besok, 09:00 AM\n- **Kalender:** Primary Google Calendar\n- **Notifikasi:** Alarm aktif 10 menit sebelum acara.`

  return {
    textContent,
    intent: {
      toolName: 'dispatch_side_agent',
      service: 'calendar',
      status: 'completed',
      summaryText: `Side Agent: Calendar Scheduled (${reminderTitle})`,
    },
    sideAgent,
  }
}

// 5. Visual Asset Generator (Image / Diagram)
export function generateVisualAssetOutput(prompt: string): GeneratedAssistantOutput {
  const imageTitle = prompt.length > 40 ? prompt.slice(0, 40) + '...' : prompt
  const newArtId = `art-img-${Date.now()}`
  const sampleImageSvg = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="800" height="450" viewBox="0 0 800 450"><defs><linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%231a1a24"/><stop offset="50%" stop-color="%232b2250"/><stop offset="100%" stop-color="%23ff5e00"/></linearGradient></defs><rect width="800" height="450" fill="url(%23g)" rx="24"/><circle cx="400" cy="180" r="70" fill="%23ffffff" fill-opacity="0.1" stroke="%23ff5e00" stroke-width="3"/><path d="M360,180 L440,180 M400,140 L400,220" stroke="%23ffffff" stroke-width="3" stroke-linecap="round"/><text x="400" y="300" fill="%23ffffff" font-family="system-ui, sans-serif" font-size="20" font-weight="bold" text-anchor="middle">ContextForge AI Generator</text><text x="400" y="335" fill="%23ffb088" font-family="monospace" font-size="13" text-anchor="middle">${encodeURIComponent(prompt.slice(0, 45))}</text></svg>`

  const newArtifact: Artifact = {
    id: newArtId,
    type: 'image_asset',
    title: `Generated: ${imageTitle}`,
    content: `# Visual Asset: ${imageTitle}\n\n![Design Preview](${sampleImageSvg})\n\n- **Model:** Google Imagen 3 / Flux.1\n- **Resolution:** 1024x1024 (HD)\n`,
    imageUrl: sampleImageSvg,
    imagePrompt: prompt,
    serviceOrigin: 'imagen',
    createdAt: 'Just now',
  }

  const sideAgent: SideAgentExecution = {
    id: `sa-img-${Date.now()}`,
    agentId: 'agent-frontend-arch',
    agentName: 'Visual & Asset Generator',
    agentRole: 'Side Agent: GPU Asset Renderer',
    avatarColor: 'bg-[#ff5e00]',
    taskGoal: `Render visual asset: "${imageTitle}"`,
    actionType: 'image_render',
    targetResource: 'GPU Pipeline (1024x1024 SVG/PNG)',
    status: 'completed',
    riskLevel: 'low_risk',
    executionTimeMs: 1450,
    tokensUsed: { input: 320, output: 85 },
    logs: [
      `[VisualWorker] Initializing GPU rendering pipeline...`,
      `[VisualWorker] Compiling prompt embeddings and style modifiers...`,
      `[VisualWorker] Diffusion steps completed (24/24 steps)...`,
      `[VisualWorker] Safety classifier scan: Clean (0 warnings). Artifact saved.`,
    ],
    summary: `High-resolution visual design rendered and stored as SVG/PNG asset.`,
    artifactId: newArtId,
  }

  const textContent = `🎨 **Visual Asset Berhasil Di-render!**\n\nDesain visual untuk **"${imageTitle}"** telah selesai dibuat oleh GPU Side Agent:\n\n![Visual Preview](${sampleImageSvg})\n\n- **Resolusi:** 1024x1024 HD (SVG/PNG)\n- **Render Engine:** GPU Diffusion Sandbox (1.45s)`

  return {
    textContent,
    intent: {
      toolName: 'dispatch_side_agent',
      service: 'imagen',
      status: 'completed',
      summaryText: `Side Agent: Visual Asset Generated (${imageTitle})`,
    },
    sideAgent,
    artifact: newArtifact,
  }
}

// 6. Direct Reasoning & Architecture Analysis (Pure Read-Only)
export function generateGeneralReasoningOutput(prompt: string): GeneratedAssistantOutput {
  let analysis = `Berikut adalah analisis mendalam terkait: **"${prompt}"**:\n\n`

  if (prompt.toLowerCase().includes('microservices') || prompt.toLowerCase().includes('monolith')) {
    analysis += `### 🏛️ Perbandingan Arsitektur: Microservices vs Modular Monolith

| Kriteria | Modular Monolith | Microservices |
| :--- | :--- | :--- |
| **Kompleksitas Operasional** | 🟢 Rendah (1 deployment pipeline) | 🔴 Tinggi (K8s, service mesh, tracing) |
| **Batas Domain (Boundaries)**| 🟢 Modul terpisah di satu repo | 🟢 Service terpisah di repo/container |
| **Kecepatan Development**   | 🚀 Sangat cepat untuk tim < 25 org | ⚠️ Butuh koordinasi API contract |
| **Latensi Antar-Modul**     | ⚡ In-memory function call (~0ms) | 🌐 Network call / gRPC (5-50ms) |

### 💡 Rekomendasi untuk ContextForge:
Mulai dengan **Modular Monolith** terlebih dahulu. Pisahkan domain code (Chat, Agents, Knowledge, Integrations) ke dalam modul TypeScript yang terisolasi dengan public interface yang jelas. Anda selalu bisa memecahnya menjadi microservice independen ketika traffic atau tim berkembang.`
  } else {
    analysis += `Sebagai **Main Orchestrator Agent**, saya memproses pertanyaan Anda dalam mode *read-only* (tanpa memodifikasi file atau menjalankan perintah berbahaya).\n\n1. **Prinsip Utama:** Setiap kebutuhan eksekusi (seperti membuat catatan di Obsidian, menulis kode, atau menjalankan CLI) akan didelegasikan secara terisolasi ke Side Agent.\n2. **Kesiapan Aksi:** Jika Anda ingin saya membuatkan catatan rangkuman di Obsidian atau menghasilkan kode implementasi, cukup ketik instruksi Anda.`
  }

  return {
    textContent: analysis,
  }
}
