-- =====================================================================
-- ContextForge: Initial Seed Data (v2.0.0)
-- Based on 4 Core Pillars: Knowledge, MCP, Skills, Agents
-- =====================================================================

-- 1. Initial Knowledge Sources (Clean by default - populated dynamically by user)
-- No dummy rows inserted

-- 2. Initial User Memories
INSERT INTO user_memories (id, category, key, value)
VALUES
    ('e287a329-873b-4813-9aa6-ffda2a7cc3f6', 'profile', 'primary_role', 'Lead Fullstack & AI Systems Architect specializing in TypeScript, NestJS, and Gemini models.'),
    ('4b90e960-93a8-48b4-93f8-8ae92be162ea', 'preference', 'code_style', 'Prefers Clean Modular Architecture, Zero ORM overhead with Native SQL, Strict TypeScript typing, and warm-editorial UI design.'),
    ('a39a2d04-18ef-4933-9799-d419b5bfb4f9', 'project', 'current_mission', 'Building ContextForge - AI-First Conversational Workspace & Agentic Control Plane.')
ON CONFLICT (id) DO NOTHING;

-- 3. Initial Activity Logs
INSERT INTO activity_logs (id, agent_id, agent_name, action_type, summary, details, status)
VALUES
    ('d9283f50-cb2d-4ba6-a496-e2aa21919864', 'agent-personal-assistant', 'Personal Assistant Agent', 'task_dispatched', 'Initialized ContextForge backend workspace and database connection.', '{"environment": "local_dev"}', 'info')
ON CONFLICT (id) DO NOTHING;

-- 4. Initial Workspace Agents
INSERT INTO workspace_agents (id, name, role, agent_type, permissions, description, avatar_color, model, temperature, system_prompt, capabilities, assigned_tools, assigned_skills, status, total_tasks_completed, success_rate_pct)
VALUES
    ('agent-personal-assistant', 'Personal Assistant Agent', 'Primary Personal Assistant & Master Orchestrator', 'orchestrator', 'sandbox_write', 'Primary host agent responsible for understanding user goals, multi-turn reasoning, memory recall, and coordinating direct MCP tool executions and research sub-agents.', 'bg-primary', 'gemini-3.5-flash', 0.2, 'You are ContextForge Personal Assistant Agent. You are the central reasoning brain and orchestrator. You handle natural dialogue, strategic planning, direct MCP tool execution, and delegate deep literature investigation to the Research Specialist Agent.', '[{"id":"c1","name":"Goal Understanding & Intent Analysis","description":"Comprehend user goals, context, and complex intent via multi-turn reasoning"},{"id":"c2","name":"Strategic Planning & Decomposition","description":"Decompose user objectives into structured execution plans and milestone steps"},{"id":"c3","name":"Direct MCP Tool & Sub-Agent Orchestration","description":"Coordinate tools directly and delegate specialized deep literature analysis to the Research Agent"}]'::jsonb, ARRAY['web_search', 'search_knowledge_vault', 'obsidian_write_note', 'obsidian_read_note', 'obsidian_create_daily_note', 'notion_get_tasks', 'notion_search', 'notion_create_page', 'create_scheduled_automation', 'transfer_to_agent'], ARRAY['skill-rfc-architect'], 'idle', 142, 99.6),
    ('agent-research', 'Research Specialist Agent', 'Information Retrieval & Grounding Intelligence', 'researcher', 'read_only', 'Dedicated intelligence sub-agent for live web research grounding, source verification, and internal semantic vector retrieval (pgvector RAG).', 'bg-[#3b6ea5]', 'gemini-3.5-flash', 0.2, 'You are Research Specialist Agent in ContextForge AI Workspace. Search, read, and analyze information from live web sources and indexed vector knowledge bases, synthesizing cited analytical answers.', '[{"id":"c4","name":"Live Web Grounding & Citations","description":"Query Google Search, verify source authority, and synthesize cited findings"},{"id":"c5","name":"Internal Semantic Vector RAG","description":"Search indexed knowledge vault and vector embeddings for technical context"},{"id":"c6","name":"Cross-Source Information Synthesis","description":"Cross-reference data across web, documents, and memory into cohesive reports"}]'::jsonb, ARRAY['web_search', 'search_knowledge_vault', 'obsidian_read_note', 'notion_search', 'transfer_to_agent'], ARRAY['skill-deep-web-research'], 'idle', 86, 99.4)
ON CONFLICT (id) DO NOTHING;

-- 5. Initial Workspace Skills
INSERT INTO workspace_skills (id, name, description, category, icon, sop_summary, instructions, assigned_tools, enabled, is_custom)
VALUES
    ('skill-rfc-architect', 'Architecture RFC & Decision Records', 'Standard operating procedure for drafting comprehensive technical design docs (TDD) and architecture decision records (ADR).', 'engineering', 'book-open', 'Enforces strict section hierarchy: Executive Summary, System Architecture, SQL DDL Schema, API Specifications, and Rollout Strategy.', 'Follow the RFC template: 1. Executive Summary, 2. High-Level Mermaid Architecture, 3. Relational/Vector Schema, 4. REST & SSE Contract, 5. Step-by-Step Implementation.', ARRAY['read_file', 'obsidian_vault_writer'], true, false),
    ('skill-deep-web-research', 'Deep Web Synthesis & Citation Grounding', 'Structured research playbook that queries search engines, evaluates source authority, and synthesizes cited answers.', 'knowledge', 'globe', 'Formulate multi-angle search queries, extract primary domain sources, filter commercial noise, and append numbered markdown footnotes.', 'Execute web search queries, verify 2+ sources, synthesize findings, cite domain URLs.', ARRAY['web_search'], true, false),
    ('skill-obsidian-vault-synthesis', 'Obsidian Vault Note Ingestion & Linking', 'Playbook for writing bi-directionally linked Markdown files with frontmatter tags and Obsidian YAML metadata.', 'knowledge', 'book-open', 'Structures frontmatter YAML (created, tags, aliases), uses [[WikiLinks]] for cross-note referencing, and writes atomic notes.', 'Format YAML frontmatter with date and tags, write concise markdown, link related topics.', ARRAY['obsidian_vault_writer', 'obsidian_vault_reader'], true, false),
    ('skill-ast-code-patcher', 'AST-Verified Code Patching & Refactoring', 'Strict code modification playbook that checks Abstract Syntax Trees (AST) before applying file diffs.', 'engineering', 'cpu', 'Generates minimal unified diffs, runs AST parsing to prevent syntax breakage, and verifies unit test passing.', 'Inspect original code, generate atomic diff, run syntax check, format output cleanly.', ARRAY['code_editor', 'code_ast_checker', 'bash_executor'], true, false),
    ('skill-threat-model-review', 'CVE & Security Threat Model Review', 'Standard protocol for auditing authentication boundaries, SQL injection risks, and secret leakage.', 'security', 'shield', 'Applies STRIDE threat modeling methodology, checks for hardcoded tokens, and verifies SQL parameterization.', 'Audit code for unsanitized inputs, check CORS and auth boundaries, document mitigations.', ARRAY['code_ast_checker', 'read_file'], true, false)
ON CONFLICT (id) DO NOTHING;

-- 6. Initial Workspace Integrations (MCP Connectors)
INSERT INTO workspace_integrations (id, name, category, status, endpoint, version, transport, auth_type, auth_config, description, tools, last_ping_ms, latency_ms, is_custom)
VALUES
    ('int-obsidian-vault-mcp', 'Obsidian Vault MCP Bridge', 'mcp_server', 'connected', 'browser-bridge://localhost:3001/api/obsidian-bridge/ws', 'v2.2.0', 'websocket_bridge', 'none', '{}'::jsonb, 'Direct bi-directional Model Context Protocol bridge into local Obsidian vault files & dynamic folder discovery.', '[{"id":"t-obs-1","name":"obsidian_get_vault_info","description":"Get status, name, and connection state of the paired Obsidian vault","readOnly":true},{"id":"t-obs-2","name":"obsidian_list_folders","description":"List all subfolders in the Obsidian vault or inside a specific relative path","readOnly":true},{"id":"t-obs-3","name":"obsidian_find_folder","description":"Search for existing folders in the vault matching a keyword or phrase","readOnly":true},{"id":"t-obs-4","name":"obsidian_create_folder","description":"Create a new folder or nested directory path in the Obsidian vault","readOnly":false},{"id":"t-obs-5","name":"obsidian_list_files","description":"List files in a specific vault folder with optional extension filter","readOnly":true},{"id":"t-obs-6","name":"obsidian_search_files","description":"Search notes across the vault by title or full text markdown content","readOnly":true},{"id":"t-obs-7","name":"obsidian_read_note","description":"Read the complete Markdown content of a specific note in the vault","readOnly":true},{"id":"t-obs-8","name":"obsidian_write_note","description":"Create or update a Markdown note with YAML frontmatter in the vault","readOnly":false},{"id":"t-obs-9","name":"obsidian_create_daily_note","description":"Append or create an entry in today daily scratchpad note","readOnly":false},{"id":"t-obs-10","name":"obsidian_delete_file","description":"Permanently delete a Markdown note from the Obsidian vault","readOnly":false},{"id":"t-obs-11","name":"obsidian_move_file","description":"Move or rename a note from sourcePath to targetPath in the vault","readOnly":false},{"id":"t-obs-12","name":"obsidian_search_backlinks","description":"Extract bi-directional link graphs and wikilink references [[targetNote]] across vault","readOnly":true}]'::jsonb, 14, 11, false),
    ('int-notion-mcp', 'Notion Workspace MCP Server', 'mcp_server', 'connected', 'https://mcp.notion.com/mcp', 'v1.2.0', 'streamable_http', 'oauth', '{"workspaceName": "ContextForge Workspace"}'::jsonb, 'Official Model Context Protocol server for Notion workspace databases, page trees, and document sync.', '[{"id":"t-notion-1","name":"notion_search","description":"Search pages and database titles across Notion workspace","readOnly":true},{"id":"t-notion-2","name":"notion_get_tasks","description":"Retrieve active task boards and database items from Notion","readOnly":true},{"id":"t-notion-3","name":"notion_read_page","description":"Read blocks, markdown content, and page properties from Notion","readOnly":true},{"id":"t-notion-4","name":"notion_create_page","description":"Create new child pages and structured document entries in Notion","readOnly":false},{"id":"t-notion-5","name":"notion_update_database","description":"Insert records and update schema rows in Notion databases","readOnly":false},{"id":"t-notion-6","name":"notion_query_database","description":"Filter and sort structured records inside Notion databases","readOnly":true}]'::jsonb, 16, 14, false),
    ('int-google-calendar-mcp', 'Google Calendar MCP Server', 'productivity', 'disconnected', 'https://www.googleapis.com/calendar/v3', 'v1.0.0', 'streamable_http', 'oauth2', '{"token": ""}'::jsonb, 'Model Context Protocol server for Google Calendar events, scheduling, attendees, and availability.', '[{"id":"t-gcal-1","name":"google_calendar_list_calendars","description":"List all Google Calendars in user account","readOnly":true},{"id":"t-gcal-2","name":"google_calendar_list_events","description":"List and search events in Google Calendar","readOnly":true},{"id":"t-gcal-3","name":"google_calendar_get_event","description":"Get detailed information for a specific Google Calendar event","readOnly":true},{"id":"t-gcal-4","name":"google_calendar_create_event","description":"Create a new meeting or event in Google Calendar","readOnly":false},{"id":"t-gcal-5","name":"google_calendar_update_event","description":"Update an existing event in Google Calendar","readOnly":false},{"id":"t-gcal-6","name":"google_calendar_delete_event","description":"Delete an event from Google Calendar","readOnly":false},{"id":"t-gcal-7","name":"google_calendar_check_availability","description":"Check free/busy availability across calendars","readOnly":true}]'::jsonb, 25, 20, false),
    ('int-android-bridge-mcp', 'Android Bridge & Digital Wellbeing MCP', 'productivity', 'connected', 'http://127.0.0.1:8080', 'v1.0.0', 'streamable_http', 'none', '{"deviceName": "Android Native MCP Device"}'::jsonb, 'Model Context Protocol bridge for Android device telemetry, Digital Wellbeing analytics, app limits, blocking, and DND controls.', '[{"id":"t-android-1","name":"android_get_device_status","description":"Check whether the Android MCP Bridge server is active, accessible, and running on the connected mobile device","readOnly":true},{"id":"t-android-2","name":"android_get_usage","description":"Retrieve raw application usage metrics and foreground screen time durations recorded since 00:00 today","readOnly":true},{"id":"t-android-3","name":"android_get_usage_summary","description":"Fetch structured daily Digital Wellbeing telemetry including total screen time, breakdown of top used apps, and most distracting applications for AI analysis","readOnly":true},{"id":"t-android-4","name":"android_get_foreground_app","description":"Detect the package name of the application currently active on the device screen in real time","readOnly":true},{"id":"t-android-5","name":"android_set_app_limit","description":"Set a maximum daily usage time limit in minutes for a specific application package","readOnly":false},{"id":"t-android-6","name":"android_block_app","description":"Instantly block or unblock an application on the Android device","readOnly":false},{"id":"t-android-7","name":"android_get_active_restrictions","description":"Retrieve all configured daily time limits and the active list of currently blocked applications on the device","readOnly":true},{"id":"t-android-8","name":"android_set_dnd","description":"Toggle Do Not Disturb (DND) mode on the Android device to suppress notification alerts during focused work sessions","readOnly":false},{"id":"t-android-9","name":"android_send_notification","description":"Send a local push notification / alert banner to the Android device status bar","readOnly":false}]'::jsonb, 18, 12, false)
ON CONFLICT (id) DO NOTHING;
